---
apiVersion: v1
kind: Namespace
metadata:
  name: samba
---
apiVersion: v1
kind: Secret
metadata:
  name: samba
  namespace: samba
type: Opaque
stringData:
  username: TODO
  password: TODO
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: samba
provisioner: smb.csi.k8s.io
parameters:
  source: //HOST/SHARE
  csi.storage.k8s.io/provisioner-secret-name: samba
  csi.storage.k8s.io/provisioner-secret-namespace: samba
  csi.storage.k8s.io/node-stage-secret-name: samba
  csi.storage.k8s.io/node-stage-secret-namespace: samba
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-samba
  namespace: samba
  labels:
    app: nginx
spec:
  serviceName: statefulset-samba
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: statefulset-smb
          image: mcr.microsoft.com/oss/nginx/nginx:1.19.5
          command:
            - "/bin/bash"
            - "-c"
            - set -euo pipefail; while true; do echo $(date) >> /mnt/smb/outfile; sleep 1; done
          volumeMounts:
            - name: persistent-storage
              mountPath: /mnt/smb
              readOnly: false
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  volumeClaimTemplates:
    - metadata:
        name: persistent-storage
      spec:
        storageClassName: samba
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
